[package]
name = "pyarraypool"
version = "0.1.2"
edition = "2021"

[lib]
name = "pyarraypool"
crate-type = ["cdylib"]

[dependencies]
shared_memory = "0.12.4"
thiserror = "1.0.32"
pyo3 = { version = "0.16.4", features = ["extension-module"] }

[dev-dependencies]
anyhow = "1.0.62"
