[package]
name = "pyarraypool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallstr = "0.3.0"
smallvec = "1.9.0"
thiserror = "1.0.32"
